add_library(
    c_fingerprint_identification_lib
    STATIC
        image/stb.c
        image/image.c
        image/bit_image.c
        image_processing/destair_holt.c
        image_processing/morphological_image_processing.c
        image_processing/thinning_zhang_suen.c
        fingerprint_minutae/fingerprint_minutae.c
)

target_include_directories(
    c_fingerprint_identification_lib
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/image
        ${CMAKE_CURRENT_SOURCE_DIR}/image_processing
)
